service        = "product"
container_name = "product"
container_port = "3001"
imageurl       = "426857564226.dkr.ecr.us-east-2.amazonaws.com/lms-order-ms:latest"
environment    = "dev"
application    = "product-service"
owner          = "adex-lms"
region         = "us-east-2"
